# Generated by Django 3.2.4 on 2021-07-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_oferta',
            field=models.IntegerField(),
        ),
    ]
